<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>5</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Polymita</AssemblyName>
    <TargetExt>.gha</TargetExt>
    <RhinoRoot Condition="'$(RhinoRoot)' == ''">C:\Program Files\Rhino 8</RhinoRoot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\*.cs" />
    <Reference Include="Grasshopper"><HintPath>$(RhinoRoot)\Plug-ins\Grasshopper\Grasshopper.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="GH_IO"><HintPath>$(RhinoRoot)\Plug-ins\Grasshopper\GH_IO.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="RhinoCommon"><HintPath>$(RhinoRoot)\System\RhinoCommon.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="RhinoWindows"><HintPath>$(RhinoRoot)\System\RhinoWindows.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="lib\harmony-2.3.3\lib\net48\0Harmony.dll"><Link>runtimes\net48\0Harmony.dll</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content>
    <Content Include="lib\harmony-2.3.3\lib\net7.0\0Harmony.dll"><Link>runtimes\net7.0\0Harmony.dll</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content>
    <Content Include="lib\harmony-2.3.3\lib\net8.0\0Harmony.dll"><Link>runtimes\net8.0\0Harmony.dll</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content>
  </ItemGroup>
</Project>

